# Generated by Django 5.2.16 on 2026-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysisresult",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Classifier 'notumor' বলেছে কিন্তু segmentation উল্লেখযোগ্য tumor area পেয়েছে — ম্যানুয়াল review দরকার",
            ),
        ),
    ]
