# Generated by Django 5.2.16 on 2026-07-29 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_aianalysisresult_needs_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologistReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved — AI ফলাফল সঠিক"),
                            ("rejected", "Rejected — AI ফলাফল ভুল"),
                            ("modified", "Modified — radiologist সংশোধন করেছে"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, help_text="Radiologist-এর ক্লিনিক্যাল পর্যবেক্ষণ/মন্তব্য"
                    ),
                ),
                (
                    "corrected_classification",
                    models.CharField(
                        blank=True,
                        help_text="AI-এর classification ভুল হলে radiologist-এর সঠিক মত (ঐচ্ছিক)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        limit_choices_to={"role": "radiologist"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiologist_review",
                        to="scans.mriscan",
                    ),
                ),
            ],
        ),
    ]
