# Generated by Django 5.2.16 on 2026-07-30 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0003_radiologistreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinical_assessment",
                    models.TextField(
                        help_text="Doctor-এর সামগ্রিক ক্লিনিক্যাল মূল্যায়ন (AI + radiologist review বিবেচনা করে)"
                    ),
                ),
                (
                    "treatment_recommendation",
                    models.TextField(
                        blank=True,
                        help_text="প্রস্তাবিত চিকিৎসা পরিকল্পনা / পরবর্তী পদক্ষেপ",
                    ),
                ),
                ("consulted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_consultation",
                        to="scans.mriscan",
                    ),
                ),
            ],
        ),
    ]
