# Generated by Django 5.2.16 on 2026-07-30 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0004_doctorconsultation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_diagnosis",
                    models.CharField(
                        help_text="চূড়ান্ত diagnosis -- radiologist-এর corrected_classification থাকলে সেটা, নাহলে AI-এর classification (view-তে auto-নির্ধারিত)",
                        max_length=50,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Doctor-এর লেখা সামগ্রিক সারসংক্ষেপ, patient-এর জন্য বোধগম্য ভাষায়"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — এখনো approve হয়নি"),
                            ("approved", "Approved — patient দেখতে পারবে"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_report",
                        to="scans.mriscan",
                    ),
                ),
            ],
        ),
    ]
